common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: sircharles
  password:

development:
  <<: *common
  database: new_bill_oyst_development

test:
  <<: *common
  database: new_bill_oyst_test


production:
  <<: *common
  database: new_bill_oyst_production
